spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:YEVTx_eanbdnQWR75en1filBQ18UHLj5D021rVyAxevEFX-0@7201aebf-b658-4a74-880a-82d6abfa1f8f.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false


server:
  port: 0

  eureka:
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}