spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:q30i7u2p3j5XF3frP9ol4-Z0p1v0ex-OY8RpwVEC18h-_zeq@3af62792-6ea9-433c-89f8-302c67d9825a.asia-southeast1.firestore.goog:443/db-capstone-2?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false


server:
  port: 0

  eureka:
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}