spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:B4_RfIjmIOMevQcFZFblmFfM-dW8WK1YUS9ruQ_IZX1tFPjW@a6c75565-b8e2-4110-bd51-9e32c1c89eaf.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false


server:
  port: 0

  eureka:
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}