spring:
  cloud:
    gateway:
      server:
        webflux:
          actuator:
            verbose:
              enabled: true
          routes:
            - id: student-service
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/v1/students,/api/v1/students/**

            - id: program-service
              uri: lb://PROGRAM-SERVICE
              predicates:
                - Path=/api/v1/programs,/api/v1/programs/**

            - id: enrollment-service
              uri: lb://ENROLLMENT-SERVICE
              predicates:
                - Path=/api/v1/enrollments,/api/v1/enrollments/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 7000

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,gateway
